# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGF9uhGp6afM8CYonEND9EyktYq7OuYU
"""

#Question No: 2
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["figure.figsize"] = (10,8)

beta = [0.02,0.7,0.06]
mue = [0.7,0.1,0.09]
sigma = [0.02,0.3,0.5]
r_0 = [0.1,0.2,0.02]

def CIR_model(beta,mue,t,T,sig,r):
  gamma = np.sqrt(beta**2+2*sig**2)
  x = T-t
  B = (2*np.exp(gamma*x)-1)/((gamma+beta)*(np.exp(gamma*x)-1)+2*gamma)
  A = ((2*gamma*np.exp((beta+gamma)*(x/2)))/(((gamma+beta)*(np.exp(gamma*x)-1)+2*gamma)))**(2*beta*mue/(sig**2))
  result = A*np.exp(-1*B*r)
  return result

T = 1
t = np.linspace(0,T,10)

for i in range(0,3):
  value = np.zeros((1,10)).ravel()
  for j in range(0,10):
    temp = CIR_model(beta[i],mue[i],t[j],T,sigma[i],r_0[i])
    value[j] = np.log(temp)/(t[j]-T)
  plt.plot(t,value,'-*')
  plt.xlabel('t',size=10)
  plt.ylabel('r',size=10)
  str = "Yield vs time(t) -- Set:{}".format(i+1)
  plt.title(str,size=15)
  plt.grid()
  plt.show()

T = np.linspace(0.1,1,600)
r = np.linspace(0.1,1,10)
t = 0
for i in range(0,1):
  for k in range(0,10):
    value = np.zeros((1,600)).ravel()
    for j in range(0,600):
      temp = CIR_model(beta[i],mue[i],t,T[j],sigma[i],r[k])
      value[j] = np.log(temp)/(t-T[j])
    plt.plot(T,value)
  plt.xlabel('T',size=15)
  plt.ylabel('r',size=15)
  str = "Yield vs Maturity(T)"
  plt.title(str,size=15)
  plt.grid()
  plt.show()